### ISSUE TITLE
Error with disabled days

### ISSUE THREAD

**Issue by postb99** [OSAMES/ionic-datepicker#7]
From @fgagneten 2 days ago on original's project as comment in this thread: https://github.com/rajeshwarpatlolla/ionic-datepicker/issues/297

There is such a big error. Please, see this video to know what's going on with this fork:
https://streamable.com/0xic0

Using the original library this error not happening. Please, is too important to solve the problem when you limit the first and the last day in the calendar

**Comment by postb99** [comment]
Please @fgagneten can you give me the configuration you used for the disabled dates.

I start working on it but have few time until Saturday.

As for your other question, about using bower, we usually install projects as bower packages. This is the npm/bower world, but you can live without it, however it's interesting to learn and once you master it you don't have problems with it. Ionic sample app uses it too, if I am right.

**Comment by postb99** [comment]
I see two bugs, after setting a "from/to" period that doesn't start at day 1 of a month and doesn't end at last day of month:
- the days before the start date's month and after the end date's month are available in the month selector.
- the start and end days must be taken into account when changing month and keeping the same day. 

I need to update my comparison test project too, so that the day is kept when changing month, with original's project master which is ahead the last released version, since I installed the packaged version.

**Comment by fgagneten** [comment]
This is my configuration:

```javascript
 var ipObj1 = {
     callback: callback,
     inputDate: new Date(),
     titleLabel: 'Seleccione una fecha',
     setLabel: 'Cancelar',
     todayLabel: 'Hoy',
     closeLabel: 'Aceptar',
     mondayFirst: true,
     from: new Date(2016, 2, 1),
     to: new Date(2017, 6, 15),
     weeksList: ["D", "L", "M", "MI", "J", "V", "S"],
     monthsList: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
     templateType: 'popup',
     showTodayButton: false,
     dateFormat: 'dd MMMM yyyy',

      closeOnSelect: false
 };
```
I set my from and to programatically, but please, see this video to
understand what happens:
https://streamable.com/0xic0

Faustino Gagneten.-

Edit by Xarkam: fusion.

**Comment by fgagneten** [comment]
I set my from and to programatically, but please, see this video to
understand what happens:
https://streamable.com/0xic0

Faustino Gagneten.-

2017-05-22 8:24 GMT-03:00 Faustino Gagneten <fgagneten@gmail.com>:

**Comment by Xarkam** [comment]
@fgagneten I decide to freeze any development until next week.

Please, standby

**Comment by postb99** [comment]
Hi @fgagneten , glad to announce you that half of the bug is fixed, please download this release and enjoy: 
https://github.com/OSAMES/ionic-datepicker/releases/tag/fixed_next_previous_month

With any configuration, the day is correctly limited when navigation next/previous month.

Now I work on fixing the available month selection in the month list. This is buggy on original project too.

**Comment by fgagneten** [comment]
Glad to know that one part of the bug is fixed. Thanks a lot, specially @postb99 on helping us really fast!
